name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR
      id: ecr
      uses: elgohr/acr-login-action@master
      with:
        service_principal: ${{ secrets.ACR_PRINCIPAL }}
        service_principal_password: ${{ secrets.ACR_PRINCIPAL_PASSWORD }}
        tenant: ${{ secrets.TENANT }}
        registry: ${{ secrets.REGISTRY }}
        repository: ${{ secrets.REPOSITORY }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ secrets.REGISTRY }}
